aeo_multilingual.settings:
  type: config_object
  label: 'AEO Multilingual settings'
  mapping:
    enabled_content_types:
      type: sequence
      label: 'Enabled content types'
      sequence:
        type: string
    score_threshold:
      type: integer
      label: 'Score threshold'
