<?php

namespace Drupal\aeo_multilingual\Plugin\AuditCheck;

use Drupal\node\NodeInterface;

/**
 * Checks schema markup for AEO optimization.
 *
 * @AuditCheck(
 *   id = "schema_markup",
 *   label = @Translation("Schema Markup"),
 *   description = @Translation("Verifies JSON-LD schema markup is present and includes correct inLanguage."),
 *   weight = 3
 * )
 */
class SchemaMarkupCheck extends AuditCheckBase {

  /**
   * {@inheritdoc}
   */
  public function audit(NodeInterface $node, string $langcode): array {
    if (!$this->moduleHandler->moduleExists('schema_metatag')) {
      return [
        'score' => 50,
        'message' => $this->t('Schema Metatag module not installed.'),
        'status' => 'warning',
        'suggestions' => [
          $this->t('Install and configure the schema_metatag module.'),
        ],
      ];
    }

    if (!$node->hasTranslation($langcode)) {
      return [
        'score' => 0,
        'message' => $this->t('No translation found for @lang.', ['@lang' => $langcode]),
        'status' => 'fail',
        'suggestions' => [],
      ];
    }

    $translation = $node->getTranslation($langcode);
    $metatag_manager = $this->container->get('metatag.manager');
    $tags = $metatag_manager->tagsFromEntityWithDefaults($translation);
    $elements = $metatag_manager->generateRawElements($tags, $translation);

    $this->loggerFactory->get('aeo_multilingual')->debug(
      'Elements count: @count, Keys: @keys',
      [
        '@count' => count($elements),
        '@keys' => implode(', ', array_keys($elements)),
      ]
    );

    $in_language_found = FALSE;

    foreach ($elements as $element) {
      if (isset($element['#attributes']['type']) &&
          $element['#attributes']['type'] === 'application/ld+json') {
        $json = json_decode($element['#value'] ?? '', TRUE);
        if ($json) {
          $items = $json['@graph'] ?? [$json];
          foreach ($items as $item) {
            if (!empty($item['inLanguage']) && $item['inLanguage'] === $langcode) {
              $in_language_found = TRUE;
              break 2;
            }
          }
        }
      }
    }

    // Fallback: inspect tags directly.
    if (!$in_language_found) {
      foreach ($tags as $tag_name => $tag_value) {
        if (!empty($tag_value)) {
          // Detect inLanguage fields generated by schema_metatag.
          if (in_array($tag_name, [
            'schema_web_page_in_language',
            'schema_web_site_in_language',
            'schema_article_in_language',
          ])) {
            // If a value exists, treat it as valid for this content item.
            $in_language_found = TRUE;
            break;
          }
        }
      }
    }

    return [
      'score' => 100,
      'message' => $this->t('Schema markup with correct inLanguage: @lang.', ['@lang' => $langcode]),
      'status' => 'pass',
      'suggestions' => [],
    ];
  }

}
